# Generated by Django 4.1.3 on 2022-11-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileEncryption',
        ),
    ]
