# Generated by Django 4.1.1 on 2022-11-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0006_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
