# Generated by Django 4.1.1 on 2022-11-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0009_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
