# Generated by Django 4.1.1 on 2022-11-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0011_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house-images/')),
            ],
        ),
        migrations.CreateModel(
            name='HouseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=125)),
                ('rooms', models.IntegerField()),
                ('images', models.ManyToManyField(to='fileapp.houseimage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileapp.houseowner')),
            ],
        ),
    ]
