# Generated by Django 4.1.1 on 2022-11-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0012_houseimage_houseowner_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
        migrations.DeleteModel(
            name='HouseOwner',
        ),
    ]
