# Generated by Django 4.1.1 on 2022-11-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0014_houseimage_houseowner_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseimage',
            name='image_name',
            field=models.CharField(default='House Name', max_length=125),
            preserve_default=False,
        ),
    ]
