# Generated by Django 4.1.1 on 2022-11-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0015_houseimage_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
