# Generated by Django 4.1.1 on 2022-12-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0017_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
